<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text Info</name>
   <tag></tag>
   <elementGuidId>940f667e-e4e3-45cd-aa84-32b1bfec0a62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.infoText--ZaA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dd5e438f-c5c5-42f5-afaa-b36fe48605e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>infoText--ZaA</value>
      <webElementGuid>47634f79-d6e9-49d3-9a1f-956e6711dd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>restorePasswordInfoText</value>
      <webElementGuid>07387c35-d0e9-4571-aaf7-fb96e7e4722a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter your username or email to help us identify you.</value>
      <webElementGuid>c4af81ee-1408-4562-8bde-03cb8f9b3c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container--1qx&quot;]/div[@class=&quot;actionsWrapper--2W0&quot;]/div[@class=&quot;actionsContent--10t&quot;]/div[@class=&quot;infoText--ZaA&quot;]</value>
      <webElementGuid>cff3e694-3114-403c-9d16-118d18341ae1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div</value>
      <webElementGuid>6dc12e44-a33a-4ebf-8bf2-d12b6aae1bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password? Don’t worry.'])[1]/following::div[1]</value>
      <webElementGuid>76c2a8d4-22bc-4e33-bc89-2ea4b024ce75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript required'])[1]/following::div[6]</value>
      <webElementGuid>f8d9cb15-3515-492e-ae32-d4c7f4806e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User name or email'])[1]/preceding::div[1]</value>
      <webElementGuid>eb5ba546-37c4-4974-8cd9-cc16f0e65702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::div[6]</value>
      <webElementGuid>f69fd2ce-59ea-4893-ba41-5140a0df10e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter your username or email to help us identify you.']/parent::*</value>
      <webElementGuid>d879c643-6797-4ae4-a8fb-50f2fd9d217a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>2ba32e47-433f-457c-ac75-20be0be702a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Enter your username or email to help us identify you.' or . = 'Enter your username or email to help us identify you.')]</value>
      <webElementGuid>b44bacdb-4b4d-4b82-9a08-5b3b75a52309</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
