<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title Forgot Password</name>
   <tag></tag>
   <elementGuidId>77a8c38b-252f-4a76-b97e-97ff6cbd73c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.title--2Mx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>bb8d6969-2a8e-4671-967a-ed2b9c966c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title--2Mx</value>
      <webElementGuid>03fcdb20-40de-441b-aee3-bb9b3db977d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>restorePasswordTitle</value>
      <webElementGuid>323ec475-8bb0-45ec-bd89-d5cbfa2dcd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot Password? Don’t worry.</value>
      <webElementGuid>0df4c71a-4431-40f7-beeb-46cc0f79b652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container--1qx&quot;]/div[@class=&quot;actionsWrapper--2W0&quot;]/div[@class=&quot;actionsContent--10t&quot;]/h1[@class=&quot;title--2Mx&quot;]</value>
      <webElementGuid>8bb82336-f892-47ad-8a66-2410d01aa86a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/h1</value>
      <webElementGuid>6d93e696-f9d5-462d-bbc0-d15755c7f80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript required'])[1]/following::h1[1]</value>
      <webElementGuid>1bd90800-efc7-454e-8d0a-e3027cb09492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your username or email to help us identify you.'])[1]/preceding::h1[1]</value>
      <webElementGuid>55cbbe7c-8d6e-496d-bca0-6b3167a6e4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User name or email'])[1]/preceding::h1[1]</value>
      <webElementGuid>5aa695f8-666e-47d7-9789-86949cfda3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot Password? Don’t worry.']/parent::*</value>
      <webElementGuid>dd88454d-020f-412b-a27b-31ca669df687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/h1</value>
      <webElementGuid>3c0ebe44-c401-4848-90fb-322562b282f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Forgot Password? Don’t worry.' or . = 'Forgot Password? Don’t worry.')]</value>
      <webElementGuid>4d3cf246-b1e3-4283-809a-f85e1c99f835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
