<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Candidate ID</name>
   <tag></tag>
   <elementGuidId>a83ff44e-94d1-432d-ac4b-669af7f75073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text--2XJ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-tabs-1']/div/div/div/div/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>940d3ae6-34ef-4ed9-88ca-53b69904c7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text--2XJ</value>
      <webElementGuid>d6af5117-82db-42f0-b100-f333a5b4a3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>candidatePanel_candidateID</value>
      <webElementGuid>b94b2c57-8942-4c20-9034-f36e3cfa4db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4336397</value>
      <webElementGuid>4a553c4c-5e07-4fb3-a506-b9cbf7d330bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-1&quot;)/div[@class=&quot;details--1-t&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;sectionWrapper--3oD&quot;]/div[@class=&quot;rowWrapper--3Qm&quot;]/span[@class=&quot;text--2XJ&quot;]</value>
      <webElementGuid>ca459249-7356-4452-9bd5-b84c33373a16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-tabs-1']/div/div/div/div/div/div/span[2]</value>
      <webElementGuid>ee764d16-88d8-4f0f-a44b-2d681973820e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate number:'])[1]/following::span[1]</value>
      <webElementGuid>2b520b22-8485-4013-bf0d-c75d2a0ccca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate information'])[1]/following::span[2]</value>
      <webElementGuid>915d485d-9014-4dd6-9c4a-e9f657c66058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Added:'])[1]/preceding::span[1]</value>
      <webElementGuid>d483c443-d008-43c8-8421-2bb40166686d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last activity:'])[1]/preceding::span[3]</value>
      <webElementGuid>f4741317-6a38-4891-a641-dce1c337d0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4336397']/parent::*</value>
      <webElementGuid>2e108579-60a1-4bc4-8cba-d91a2ae3f607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span[2]</value>
      <webElementGuid>1c2ee230-b4d3-4d58-864a-4c7a46bc26a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '4336397' or . = '4336397')]</value>
      <webElementGuid>93d28fae-5a4f-41aa-94ec-67bcce8adaac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
