<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status</name>
   <tag></tag>
   <elementGuidId>1629842d-f81f-420f-9831-590926e269fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-tabs-1']/div/div/div/div/div/div[4]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0234e850-bcc6-4e49-8a95-51b0dec2ea6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text--2XJ</value>
      <webElementGuid>b8d4bfbb-b594-4a02-9604-ed89064cc81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>candidatePanel_status</value>
      <webElementGuid>e91fe7de-8085-43d0-a44a-827c288101b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Incomplete</value>
      <webElementGuid>6801287c-2867-408d-8cc3-0602faf9d3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-1&quot;)/div[@class=&quot;details--1-t&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;sectionWrapper--3oD&quot;]/div[@class=&quot;rowWrapper--3Qm&quot;]/span[@class=&quot;text--2XJ&quot;]</value>
      <webElementGuid>15e0ea82-46c8-4ef6-a43c-a4df31b4d77f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-tabs-1']/div/div/div/div/div/div[4]/span[2]</value>
      <webElementGuid>5205684b-61f3-4927-ad95-69d50a2b0d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status:'])[1]/following::span[1]</value>
      <webElementGuid>6d2e7bcf-9663-458a-bfa1-3716d7321295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last activity:'])[1]/following::span[3]</value>
      <webElementGuid>8c3c5fc6-f0b4-4c26-bc79-2af77ace024c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal information'])[1]/preceding::span[1]</value>
      <webElementGuid>370abce1-a8c6-4a12-a1ee-51a5ca647ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full name:'])[1]/preceding::span[1]</value>
      <webElementGuid>91631f6a-bd0f-4e13-841a-7c962cdf28df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span[2]</value>
      <webElementGuid>2663e6e4-2184-4b54-bdc8-aa79aae0a34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Incomplete' or . = 'Incomplete')]</value>
      <webElementGuid>597d2e9f-7f78-48fc-b1fc-ad79737d3593</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
