<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>breadcrumb Agency</name>
   <tag></tag>
   <elementGuidId>cbcee876-830d-4248-b1d4-d1250e14bbde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tag--2ea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-container']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a7a60314-328b-4340-9f1a-5cdd30767453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tag--2ea</value>
      <webElementGuid>28f5bafe-db26-49b2-bfba-06a2faf087bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>breadcrumb_agency</value>
      <webElementGuid>11f18915-d940-43bf-b20b-293b51e462e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Temp-agency 1 (Agency)</value>
      <webElementGuid>f0df17c1-dfd4-4a79-8d52-d7464240c746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-container&quot;)/div[@class=&quot;content content--3Nx&quot;]/div[@class=&quot;tags--2x9&quot;]/div[@class=&quot;tag--2ea&quot;]</value>
      <webElementGuid>ab34a29d-3338-4068-a553-97a9325f999b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-container']/div/div/div</value>
      <webElementGuid>2c922a19-2469-400d-bbf7-cf2dd27dab85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate list'])[2]/following::div[2]</value>
      <webElementGuid>1ca44287-8a42-428d-8b4c-e3bb3fc90e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Old user interface'])[1]/following::div[6]</value>
      <webElementGuid>0c15004a-db4e-410a-8279-e43a54ec3beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centraal (Unit)'])[1]/preceding::div[1]</value>
      <webElementGuid>dc050ea3-c7bc-4c2f-9d11-080cc992fb81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BEHAVIOUR Public name EN (Function)'])[1]/preceding::div[2]</value>
      <webElementGuid>8748d6f4-21cc-4ffc-ad38-1a001ac34ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Temp-agency 1 (Agency)']/parent::*</value>
      <webElementGuid>00c8b0c6-c591-4eea-bb0f-5aa399bc123d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div</value>
      <webElementGuid>1d8120d4-39a2-4a9a-9ed5-943471fc4399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Temp-agency 1 (Agency)' or . = 'Temp-agency 1 (Agency)')]</value>
      <webElementGuid>b5be2f8e-1b53-452d-9548-c05394640040</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
