<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>breadcrumb Function</name>
   <tag></tag>
   <elementGuidId>f8d11e17-3ea6-4378-accb-c3c45b18482c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-container']/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94fa489d-10e6-4fa2-991e-419e49a3dda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tag--2ea</value>
      <webElementGuid>2d125992-efc5-40ae-ab86-123432b8a110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>breadcrumb_function</value>
      <webElementGuid>aadab15b-cfc7-4d2f-bf30-3d98ff75b0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BEHAVIOUR Public name EN (Function)</value>
      <webElementGuid>95407a97-da2e-4c30-b1be-db528a6bbffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-container&quot;)/div[@class=&quot;content content--3Nx&quot;]/div[@class=&quot;tags--2x9&quot;]/div[@class=&quot;tag--2ea&quot;]</value>
      <webElementGuid>ba24c41a-dd40-4555-adaf-08c3bc2600d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-container']/div/div/div[3]</value>
      <webElementGuid>4f77b843-733c-43fc-9b02-b265a2c53135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centraal (Unit)'])[1]/following::div[1]</value>
      <webElementGuid>14db7e59-db11-4511-853c-e0776221d154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temp-agency 1 (Agency)'])[1]/following::div[2]</value>
      <webElementGuid>9633271e-431c-4d8b-8593-10ac6f86f37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INDICATOR:0 (Test)'])[1]/preceding::div[1]</value>
      <webElementGuid>b47484cd-c47e-4b74-8d41-bc63fb85ce3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imported (Status)'])[1]/preceding::div[3]</value>
      <webElementGuid>cf08030f-6012-40aa-adb9-7f286fadd1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BEHAVIOUR Public name EN (Function)']/parent::*</value>
      <webElementGuid>a895a64c-0c12-4f05-b43e-3452950c04ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[3]</value>
      <webElementGuid>4f86a963-e537-4466-99d0-2e4192ed6a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'BEHAVIOUR Public name EN (Function)' or . = 'BEHAVIOUR Public name EN (Function)')]</value>
      <webElementGuid>7ef5d392-3844-45b7-8c20-eb40d2f9655e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
