<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label Wrong username</name>
   <tag></tag>
   <elementGuidId>73e6dbd8-41e3-44c9-983a-e216cae1277e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.validationLabel--BmK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/form/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>loginUsernameValidation</value>
      <webElementGuid>fffe6892-749b-4805-8153-951ab53e6ea1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/form/div/div/div/div[2]</value>
      <webElementGuid>f3227bf6-4105-406a-bbd5-4a57579633f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User name'])[1]/following::div[4]</value>
      <webElementGuid>c594afdd-fbaa-44c3-b970-b75d898f6b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your details below.'])[1]/following::div[5]</value>
      <webElementGuid>eff7620b-4c73-4b8c-aeb2-f7662b3dafbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password:'])[1]/preceding::div[1]</value>
      <webElementGuid>01ce3a2b-f822-4bdc-99c4-4d2b5cd78034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password'])[1]/preceding::div[1]</value>
      <webElementGuid>530bf8cf-6494-41dd-90c7-11d27e7bec7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wrong credentials']/parent::*</value>
      <webElementGuid>18053212-50cf-430d-9fdb-61155b067efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div[2]</value>
      <webElementGuid>f317eb70-9f0f-4ff8-979d-cbcd70873b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Wrong credentials' or . = 'Wrong credentials')]</value>
      <webElementGuid>49c56d02-4d1f-41d5-a9d7-5d104df24bd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
