<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label User name</name>
   <tag></tag>
   <elementGuidId>57a8cc76-b3e5-4efc-ae32-51ad6268dbab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.label--1lX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/form/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>205437e9-3152-4214-801f-c326524ca5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label--1lX</value>
      <webElementGuid>abc8af91-221f-4622-bbf8-dcbd201e064b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>userNameLabel</value>
      <webElementGuid>a9d4d56d-8ad4-4904-8685-a67b64e8fa03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User name</value>
      <webElementGuid>74b4bb40-74f0-41c1-b44b-d536370b9471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container--1qx&quot;]/div[@class=&quot;actionsWrapper--2W0&quot;]/div[@class=&quot;actionsContent--10t&quot;]/form[@class=&quot;loginForm--2VC&quot;]/div[@class=&quot;controlGroup--3ay controlGrop--2ep&quot;]/label[@class=&quot;label--1lX&quot;]</value>
      <webElementGuid>c6aeed39-88fd-4d20-9052-abbdcc33cbb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/form/div/label</value>
      <webElementGuid>1033cd69-ca6d-4e32-bace-4ab6b06902a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your details below.'])[1]/following::label[1]</value>
      <webElementGuid>9b1b90dc-c9ce-445b-be23-0b5d591b21e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi! Welcome back.'])[1]/following::label[1]</value>
      <webElementGuid>f2374657-2552-410e-aac8-4fb44cb97996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password:'])[1]/preceding::label[1]</value>
      <webElementGuid>ff51c4b5-b839-41ab-bc56-caf728f608f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password'])[1]/preceding::label[2]</value>
      <webElementGuid>3e13a418-4f52-4576-a3c6-deb0de85cf17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User name']/parent::*</value>
      <webElementGuid>708cf3f3-e88b-44c4-8863-6530052f8e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>a5897a29-be64-4007-8ddd-f00e07e3a5a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'User name' or . = 'User name')]</value>
      <webElementGuid>37a0cc52-97a5-468d-be9e-5433b57749b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
