<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Send reminder</name>
   <tag></tag>
   <elementGuidId>b9cefc3b-bfd8-4602-83e0-b0cd4656c966</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button--11r.button_normal--2la.button_primary--1sD.button_with_icon--j12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>remindSendBtn</value>
      <webElementGuid>e7771d66-2d94-4b5a-81ac-e88100aabff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>914904ae-f06f-4a30-9d04-ff7e1d3c7c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>3d199ece-23e3-4446-a1fa-516ff8546eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::button[2]</value>
      <webElementGuid>1a6cd555-542c-4ea0-b3cb-86d45244c9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button[2]</value>
      <webElementGuid>950950ee-2a7f-44ce-9dc1-06197237a670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Send reminder' or . = 'Send reminder')]</value>
      <webElementGuid>59d546fe-f5f9-4427-a705-ff087e663a46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
