<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span Email</name>
   <tag></tag>
   <elementGuidId>c079a7c4-3488-49e5-aa7e-079ff95ab346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.toItem--uqv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='MatchQ Human Capital Indicators &lt;info@matchq.nl>'])[1]/following::span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e74ac803-9543-424c-9c14-6b115cd8095b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toItem--uqv</value>
      <webElementGuid>6b7d54a0-bca1-4896-85b4-4057440d73fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MatchQ Human Capital Indicators &lt;info@matchq.nl>'])[1]/following::span[2]</value>
      <webElementGuid>ec53c158-526c-4690-9465-4807e5e88180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 3 - Send the invitation'])[1]/following::span[3]</value>
      <webElementGuid>c10f701a-3981-40d9-9e26-144c03d20d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uitnodiging MatchQ e-assessment voor KATALON'])[1]/preceding::span[1]</value>
      <webElementGuid>18403b2b-9149-4a45-b378-cdbe37abc010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test@test.com']/parent::*</value>
      <webElementGuid>b4ba58d3-6f65-4226-83a2-17680666c690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span</value>
      <webElementGuid>b638d186-3087-4314-84f8-0d1fbb47c505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'test@test.com' or . = 'test@test.com')]</value>
      <webElementGuid>feb0502b-756b-4547-ba66-27c17234806f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
