<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab Details</name>
   <tag></tag>
   <elementGuidId>88c1b570-ce60-4339-bf9a-f0ce43ff4d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-tabs-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='react-tabs-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>bed54ed8-1021-44ba-b38f-24a3ecee8462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>candidatePanelDetailTab</value>
      <webElementGuid>59fb236f-95b7-42fd-a8cd-369e3bcc789d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab--3Cc selected--1eR</value>
      <webElementGuid>35eda999-57f5-447f-bf6f-30041ab34e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>562ad326-2095-4f41-a3a9-445556d280ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-tabs-0</value>
      <webElementGuid>855d36f1-f6ec-4a1e-a971-09fe364e9570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b895f5a5-af81-4a77-b0c2-230d05dc0f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>620a72f0-1233-4023-9361-28211454e5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>react-tabs-1</value>
      <webElementGuid>dfdbaf61-850c-4c08-9b65-2f4d4a4a6a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>786c2fa8-4068-479d-9eae-a714a0cc249b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rttab</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7daeea9d-3263-4a83-9de2-87a170f0b623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Details</value>
      <webElementGuid>94939d25-d0e4-4e88-88e6-1e4a9c87d7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-0&quot;)</value>
      <webElementGuid>d430891d-993f-4fd0-9762-aa19d88de540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='react-tabs-0']</value>
      <webElementGuid>294b2ddb-29d0-48fb-8924-733f2aff6453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BI+NIVO 11 DimaTEST'])[2]/following::li[1]</value>
      <webElementGuid>ae58bcd0-f5f8-42c7-a859-5c7a4cef7500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'react-tabs-0', '&quot;', ')')])[1]/following::li[1]</value>
      <webElementGuid>286a5b23-9c11-469d-b0d9-1742e7cc8cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mail history'])[1]/preceding::li[1]</value>
      <webElementGuid>93f7cdc9-f9e8-44a5-98bc-154ca0c3aeaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate information'])[1]/preceding::li[2]</value>
      <webElementGuid>32f13292-1c8a-45a1-a957-137cb5842d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Details']/parent::*</value>
      <webElementGuid>80a1c509-444d-4f12-9d75-56bbff7bf228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>617f8711-b88d-4c55-a924-0c224f166563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'react-tabs-0' and (text() = 'Details' or . = 'Details')]</value>
      <webElementGuid>4b32c24b-03f1-49b3-8d3a-edad0d2a516d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
