<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown Day</name>
   <tag></tag>
   <elementGuidId>8c92e956-653e-4e13-83c0-c92d1c501cd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-chosen-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-chosen-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-chosen-1</value>
      <webElementGuid>f0265c1d-5b51-4b86-84b5-52b4d6221d13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-chosen-1']</value>
      <webElementGuid>aca9cb04-b185-4693-bae1-a6f22836c9f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s2id_birth_d']/a/span</value>
      <webElementGuid>56e38262-10cb-4756-869c-e8c924884c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geboortedatum'])[1]/following::span[1]</value>
      <webElementGuid>3b231b33-d57d-49fe-ad75-f6a828c7b624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Achternaam'])[1]/following::span[1]</value>
      <webElementGuid>e405bd6e-c2e4-462a-a69b-247c737baf9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geboortedatum'])[2]/preceding::span[2]</value>
      <webElementGuid>b5b01f88-738e-4ed3-82fb-eecb9b48bfec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='maand'])[1]/preceding::span[2]</value>
      <webElementGuid>ee855544-b1e7-486e-8492-886b8b3e6587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='dag']/parent::*</value>
      <webElementGuid>bd3391b9-1648-4daa-91c8-4e27885b06d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>50702006-df9e-494f-b0ed-f1ec922bf1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-chosen-1' and (text() = 'dag' or . = 'dag')]</value>
      <webElementGuid>d966e6e4-a64a-4e6a-89c4-20d60bce3f0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
