<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input First Name</name>
   <tag></tag>
   <elementGuidId>8cd5bff7-668c-4a02-ab7c-9532227364bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='name_first']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name_first</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name_first</value>
      <webElementGuid>e6364d11-d148-440f-b8dd-5d7ebf3a3631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='name_first']</value>
      <webElementGuid>ead6f1cb-20e8-403d-b282-70d3f2635c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='main']/div[2]/div/input</value>
      <webElementGuid>f57f1b8c-8549-4485-b934-6ee9c5fb93e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>cc5c7d28-d0d0-43f3-8f11-48f3ce5e38b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'name_first' and @name = 'name_first' and @type = 'text']</value>
      <webElementGuid>5bf45d6c-45de-424a-925c-03b20469ae51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
