<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown Language</name>
   <tag></tag>
   <elementGuidId>fc99e07b-2cb6-46f0-814b-7cda754863fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.groupItem__btn--DpL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to page'])[1]/following::div[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cfdf938a-cc9a-448c-93e8-d3d741530e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>groupItem__btn--DpL</value>
      <webElementGuid>098899ee-6edb-4867-9dac-b32c7fe2d5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>languageDropdown</value>
      <webElementGuid>b4c672f2-3db2-4e0c-bd4b-574deaa70e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Language </value>
      <webElementGuid>b63e70f5-39c3-44b8-ae6a-9d75baaef1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;tooltipContainer--1yK&quot;]/div[@class=&quot;tooltip--KxE tooltip_fixed--Lta tooltip_lightTheme--WIa tooltip_bottomPosition--3KK&quot;]/div[@class=&quot;tooltip__content--Do-&quot;]/div[@class=&quot;content--1xf&quot;]/div[3]/div[@class=&quot;groupItem__btn--DpL&quot;]</value>
      <webElementGuid>f4d0ea04-3dda-4389-abd4-92ea59c300a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to page'])[1]/following::div[11]</value>
      <webElementGuid>76bc2fb0-9275-4d79-ab31-e0bbffdf2a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[3]/div</value>
      <webElementGuid>03fcc535-4900-4ecd-84f8-c5cc71a74f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Language ' or . = 'Language ')]</value>
      <webElementGuid>1fd38e45-35a6-43b3-a8be-90b1d0c17a9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
