<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input Prefix Name</name>
   <tag></tag>
   <elementGuidId>ebf8baaf-d5e5-4f28-918b-d47467c74d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;name_middle&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='name_middle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64f6f0dd-ab40-4d7d-8cf2-7fa38cc2ca6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>8252d536-aa02-45cb-9f3c-0974a6a47cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>965469fc-0f66-4eb1-917a-ad02564ad355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input--3G-</value>
      <webElementGuid>a06ec1fe-3e8d-4ff6-ae63-29e10ad1d749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>b8774288-751d-45dd-90a4-9088b82be084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name_middle</value>
      <webElementGuid>0a1157c4-02fe-49da-915d-dd07f0638c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>35970217-e8d4-4622-9a81-b9aaf64195df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>candidateMiddleNameInput</value>
      <webElementGuid>4971df6e-e024-4d11-81f1-be0df67dd64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-container&quot;)/div[@class=&quot;content content--3Nx&quot;]/div[@class=&quot;widgetWrapper--3SO&quot;]/div[@class=&quot;widget--pVX widget_active--JH5&quot;]/form[1]/div[@class=&quot;flexGrid--3N1&quot;]/div[@class=&quot;paddingBox--sGL paddingBox_rightSmall--2f1 paddingBox_bottomSmall--3fV&quot;]/div[@class=&quot;controlGroup--3ay controlGroup--2TV&quot;]/div[@class=&quot;component--17Y&quot;]/div[@class=&quot;textbox--24h small--30x inline--1PL&quot;]/div[@class=&quot;inner--2u7&quot;]/input[@class=&quot;input--3G-&quot;]</value>
      <webElementGuid>ca31880d-9dea-4b06-8557-82a230eb8a9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='name_middle']</value>
      <webElementGuid>609b5b5a-cfd8-4d3c-ae3c-eb427850bde2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-container']/div/div[2]/div/form/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>9f82ba70-0891-4241-a534-94be134901b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>de9ec749-d3cc-4f6b-b42f-57b3456894b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter' and @type = 'text' and @name = 'name_middle']</value>
      <webElementGuid>ef3c331b-38fa-464f-8847-b7d49f4a232f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
