<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Remove</name>
   <tag></tag>
   <elementGuidId>08e28f5a-dde9-46ce-9ea3-6e2ee3cd6b01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[15]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button--11r.button_normal--2la.button_primary--1sD</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-katalon = 'confirmationDialogConfirmBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>confirmationDialogConfirmBtn</value>
      <webElementGuid>9b43fb54-fb8c-4eeb-897e-51f9d96a6a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>7cf0be3a-62ab-42bb-9d5a-92c6b8b187e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[15]</value>
      <webElementGuid>f089e29a-cbaa-4b09-b746-c112770af186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>21b264d7-d266-46cd-a9fa-04aabf3e86be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div[2]/button[2]</value>
      <webElementGuid>0432c0e3-252f-4eb1-93ef-2b2a918d63e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Remove' or . = 'Remove')]</value>
      <webElementGuid>2c52ca91-8f81-4f0c-88a6-61eba76cf8d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
