<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Function</name>
   <tag></tag>
   <elementGuidId>66ca3ac7-ce1c-4023-b92a-3f567522ad2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-tabs-25']/div/div/div/div/div[3]/div[3]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cfa57676-6e18-4884-aa51-8f39d77a6936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text--2XJ</value>
      <webElementGuid>7f2a97d5-e5b0-4867-afbb-d1b27fcd3000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>candidatePanel_function</value>
      <webElementGuid>21116af2-1ae7-49f9-9aa3-0aa0ba755df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BI + NIVO 35</value>
      <webElementGuid>0065fd17-00a6-420a-92c8-a0e24ac62d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-25&quot;)/div[@class=&quot;details--1-t&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;sectionWrapper--3oD&quot;]/div[@class=&quot;rowWrapper--3Qm&quot;]/span[@class=&quot;text--2XJ&quot;]</value>
      <webElementGuid>fbbe3f68-2ac3-448d-b2b7-ffb8dbbb4a4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-tabs-25']/div/div/div/div/div[3]/div[3]/span[2]</value>
      <webElementGuid>ceec4070-2998-46c2-a83b-dfca9599669a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Function:'])[1]/following::span[1]</value>
      <webElementGuid>466ae49c-be83-4e91-be58-c2f1a434a3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centraal'])[1]/following::span[2]</value>
      <webElementGuid>60b1a83b-d369-4848-9cfb-1d7613913264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/span[2]</value>
      <webElementGuid>f8b2f531-6bed-4746-bf56-97c38afc9f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'BI + NIVO 35' or . = 'BI + NIVO 35')]</value>
      <webElementGuid>727ca62d-b10b-4061-8a66-0884b480e283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
