<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>City</name>
   <tag></tag>
   <elementGuidId>d4ec3576-7d37-48eb-9d89-14508653226a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-tabs-5']/div/div/div/div/div[2]/div[7]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1826623e-48cb-4ba1-bee4-b480cfc5a63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text--2XJ</value>
      <webElementGuid>385db9aa-0865-4c7f-8e72-7f33e5f9348c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>candidatePanel_city</value>
      <webElementGuid>d4541b6a-0cc2-46eb-90e6-6579ad561491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ivano-Frankivsk</value>
      <webElementGuid>d730e256-f5da-4885-ad2e-195acc17db70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-5&quot;)/div[@class=&quot;details--1-t&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;sectionWrapper--3oD&quot;]/div[@class=&quot;rowWrapper--3Qm&quot;]/span[@class=&quot;text--2XJ&quot;]</value>
      <webElementGuid>e1d497c0-6d12-4d37-8961-edc5b5a8508d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-tabs-5']/div/div/div/div/div[2]/div[7]/span[2]</value>
      <webElementGuid>1e820d8f-2faa-4d1b-b6f6-fcf277761bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City:'])[1]/following::span[1]</value>
      <webElementGuid>9dc51120-cb52-4a73-b01e-c83e0c7db70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal Code:'])[1]/following::span[3]</value>
      <webElementGuid>3a35a314-51e5-4811-ba5c-4b275fb74484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/preceding::span[1]</value>
      <webElementGuid>4dfa5ea8-f2fb-463f-bb41-7b6035604c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dborodaikevych@sharpminds.com'])[1]/preceding::span[2]</value>
      <webElementGuid>a259b7c1-d612-4c31-88a0-38e5dbb6e726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/span[2]</value>
      <webElementGuid>e6b9e655-df01-45e3-a29a-4ff4eaa0fbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ivano-Frankivsk' or . = 'Ivano-Frankivsk')]</value>
      <webElementGuid>374577b9-7c8c-4da4-a22d-b57f3f33f0d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
