<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Group Remind</name>
   <tag></tag>
   <elementGuidId>e3b062bb-1199-4c59-b0a4-208194657328</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item--2AJ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect all'])[1]/following::div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bca5d262-329e-42ed-9daa-9779df7bd996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item--2AJ</value>
      <webElementGuid>8db58f85-dc42-4b4c-a2bc-bb528a3fbd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>selectionGroupActionRemindBtn</value>
      <webElementGuid>e7c9590b-dc1d-41db-83c2-6228d9d3184d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Remind </value>
      <webElementGuid>ea1843fd-5c7f-499d-b9bc-4072db9f7237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;tooltipContainer--1yK&quot;]/div[@class=&quot;tooltip--KxE tooltip_lightTheme--WIa tooltip_bottomPosition--3KK&quot;]/div[@class=&quot;tooltip__content--Do-&quot;]/div[@class=&quot;groupActionsTooltipContent--10v&quot;]/div[2]/div[@class=&quot;item--2AJ&quot;]</value>
      <webElementGuid>6701540c-3c5b-49ca-927b-8338ed0ccf60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect all'])[1]/following::div[2]</value>
      <webElementGuid>3f8e1704-66f5-49c2-88c9-f7dde77b2e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show selected'])[1]/following::div[2]</value>
      <webElementGuid>b20023f1-6e23-4a83-bbc3-df2eb91a3a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div</value>
      <webElementGuid>3951ec88-3b48-4063-a37b-290832ba6a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Remind ' or . = ' Remind ')]</value>
      <webElementGuid>8bb4b488-be96-4f62-9070-1c4c3ca450c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
