<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Filters</name>
   <tag></tag>
   <elementGuidId>739633c4-55a1-4a2c-83a5-803db76a3794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button--11r.button_normal--2la.button_default--mM4.button_with_icon--j12.button_with_only_icon--HcX.btn--1ph</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f38b7f0-cd55-4dd1-a10f-e613cc95e71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button--11r button_normal--2la button_default--mM4 button_with_icon--j12 button_with_only_icon--HcX btn--1ph</value>
      <webElementGuid>059ff0bd-a271-4b8e-aa65-193d431dd136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72a292e1-b9ae-4918-9544-93a9306ffe2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>selectionFilterBtn</value>
      <webElementGuid>56612bc5-d949-4844-bd59-cf8cff627f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-container&quot;)/div[@class=&quot;content content--3Nx&quot;]/div[@class=&quot;topActionsWrapper--2cB&quot;]/button[@class=&quot;button--11r button_normal--2la button_default--mM4 button_with_icon--j12 button_with_only_icon--HcX btn--1ph&quot;]</value>
      <webElementGuid>5ef8f493-da7f-4cd1-9b6c-11611fb796c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>81726a12-d92c-496c-8ac3-337ebde4dbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-container']/div/div[2]/button</value>
      <webElementGuid>1eb87e21-9751-4c63-8f9e-fb3011dc6a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centraal (Unit)'])[1]/following::button[1]</value>
      <webElementGuid>71e7f866-bff1-43ba-9ae3-1f0e997ad598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite new candidate'])[1]/preceding::button[2]</value>
      <webElementGuid>5ef77364-3b76-47b6-8465-05e7d126052d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group actions'])[1]/preceding::button[3]</value>
      <webElementGuid>54d9147e-917c-4168-8d8f-ee89f3fec369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>29690894-4928-4bb4-92e1-4e068ba3391a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>c7846522-4865-41be-bf6e-1fea8d81c0f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
