<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Candidate List</name>
   <tag></tag>
   <elementGuidId>bf168cb9-4c6a-4a94-aa99-5d2008190c64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.btn--9aO.btn_activeSingleLink--2e9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/aside/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-katalon = 'menuGroupBtn_selection']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>menuGroupBtn_selection</value>
      <webElementGuid>6b4c82a5-bea0-46b2-9390-e7615815a3cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/aside/div[2]/div/div[2]</value>
      <webElementGuid>7239d66d-dea2-403d-839c-dbbfac325ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usage tiers'])[1]/following::div[1]</value>
      <webElementGuid>64651b1e-d50f-46dc-8ee4-70c186605ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agencies'])[1]/following::div[1]</value>
      <webElementGuid>e3711572-0330-4950-a7ec-1d570d5656d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Old user interface'])[1]/preceding::div[1]</value>
      <webElementGuid>2edfb24f-961c-4a46-a562-133e5c8bea6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>bafdbf77-6f73-4628-92e7-6eab086e0d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Candidate list' or . = 'Candidate list')]</value>
      <webElementGuid>92959c24-4fb9-4cd5-8259-c4b36430d2ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
