<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>number Candidates</name>
   <tag></tag>
   <elementGuidId>132ce200-2cbc-4893-881c-dce7d8901399</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.count--dQQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-container']/div/h1/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4149652e-b549-4dca-b629-779adb883314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>count--dQQ</value>
      <webElementGuid>5c54bdc9-b457-4dfb-bc37-72eeba899527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>pageTitleCount</value>
      <webElementGuid>de045c8e-0379-4a64-aaf6-7b50912ede0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>136</value>
      <webElementGuid>cfa3be62-86f7-4b6d-8e12-bf2bbd419fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-container&quot;)/div[@class=&quot;content content--3Nx&quot;]/h1[@class=&quot;title--3qK&quot;]/span[@class=&quot;count--dQQ&quot;]</value>
      <webElementGuid>65728615-12bb-4ae0-8067-bdd1dee2ccd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-container']/div/h1/span</value>
      <webElementGuid>a4f6b11d-69a1-41d7-84d8-cf5a4052b0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Old user interface'])[1]/following::span[1]</value>
      <webElementGuid>b0adb753-97f4-4f70-876b-14f2f5da667b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centraal (Unit)'])[1]/preceding::span[1]</value>
      <webElementGuid>3710849c-d994-43af-be45-184a75c71d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite new candidate'])[1]/preceding::span[2]</value>
      <webElementGuid>3a2b255d-2559-4f81-9d80-583a37c3ff71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='136']/parent::*</value>
      <webElementGuid>e4c06246-310b-4c69-9e7b-7d45e64b56c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>b835d1e1-4b10-4571-a71e-13dccf0c2da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '136' or . = '136')]</value>
      <webElementGuid>e770a28b-1ba4-4980-869c-bfac8af0b76d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
