<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page Title</name>
   <tag></tag>
   <elementGuidId>a649c2a9-df69-42a1-8df5-bf3850bd7ea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.title--3qK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-container']/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>0fbe8680-6d91-4034-9426-dcd8380f5fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title--3qK</value>
      <webElementGuid>e1ba0f76-bb19-4de7-90dc-1761a96e2bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>pageTitle</value>
      <webElementGuid>8e6580ec-d1ad-473d-b88a-85eb7a793c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Candidate list136</value>
      <webElementGuid>4062bebb-1ba4-4276-9c29-5b51cef43c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-container&quot;)/div[@class=&quot;content content--3Nx&quot;]/h1[@class=&quot;title--3qK&quot;]</value>
      <webElementGuid>7c625e4f-13f8-45ac-a486-c9b467e9d468</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-container']/div/h1</value>
      <webElementGuid>77640d4b-48b1-43d3-b5fa-9be4f5183d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Old user interface'])[1]/following::h1[1]</value>
      <webElementGuid>c7419237-3999-4960-b6bc-61dff64d3960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate list'])[1]/following::h1[1]</value>
      <webElementGuid>d8d54d69-b4cb-489d-8b2e-da1241360b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centraal (Unit)'])[1]/preceding::h1[1]</value>
      <webElementGuid>fd81d014-f24a-4fdb-ac69-cb60a9ac07da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite new candidate'])[1]/preceding::h1[1]</value>
      <webElementGuid>b205a2bc-e5f4-43e7-b6f0-80b970c3daeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/h1</value>
      <webElementGuid>3a1cadf7-4360-47a4-90b6-61519213b19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Candidate list136' or . = 'Candidate list136')]</value>
      <webElementGuid>5a326dd9-614c-47d9-ab2f-2980035520ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
