<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header Position</name>
   <tag></tag>
   <elementGuidId>ce7ee473-8851-491e-897d-3774b97fffa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.selection-list__cell--function.headCell--lwz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-container']/div/div[3]/div/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a9ed931-7b0d-422a-866a-b47a7bebec97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selection-list__cell--function headCell--lwz</value>
      <webElementGuid>75d17b10-c68d-469f-9151-495773d15242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>candidateListHeaderLabel_function</value>
      <webElementGuid>74c19a74-441c-49ba-8d6c-7a6a26980860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Position</value>
      <webElementGuid>11ba1ce1-1252-4f71-ad4d-bacb9f8ad950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-container&quot;)/div[@class=&quot;content content--3Nx&quot;]/div[@class=&quot;list--3Gh&quot;]/div[@class=&quot;header--1yZ&quot;]/div[@class=&quot;header_inner--3dc&quot;]/div[@class=&quot;selection-list__cell--function headCell--lwz&quot;]</value>
      <webElementGuid>46790990-4cb4-4e34-a716-a09adf16a9be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-container']/div/div[3]/div/div[2]/div[3]</value>
      <webElementGuid>fdd26c29-9989-480a-8d76-8d89ccd7f4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date added'])[1]/following::div[1]</value>
      <webElementGuid>1a185b8b-7dac-4995-97cf-cd92c29ef095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::div[3]</value>
      <webElementGuid>d8c8461f-0275-4d90-991a-ccadf9d8a13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agency'])[1]/preceding::div[1]</value>
      <webElementGuid>870dac41-fdc9-4642-9a63-41ddc513e339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note'])[1]/preceding::div[2]</value>
      <webElementGuid>f96128de-bee4-4685-a219-e6949041ddf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Position']/parent::*</value>
      <webElementGuid>d7267497-a354-4009-bec3-8307b7a64f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[3]</value>
      <webElementGuid>f0b976c2-8138-41e5-8606-c314348f122b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Position' or . = 'Position')]</value>
      <webElementGuid>5d1bee14-c0b4-4f9f-a930-1139415975c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
