<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>points number</name>
   <tag></tag>
   <elementGuidId>1f4039d5-6a8a-4c3a-8d33-88b5bf38be62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='main']/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3df85834-ba29-44f8-979b-2c2984c1a29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0dcc52fb-74d5-4911-92c6-e4eef40f901c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;gi&quot;]/div[@class=&quot;set&quot;]/div[@class=&quot;question question1 min&quot;]/span[@class=&quot;number&quot;]</value>
      <webElementGuid>9d4f25f3-44f3-4bc7-aa98-6739043ce902</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='main']/div/div/div/span</value>
      <webElementGuid>1c4ed693-c138-4f9c-b042-bfdd226ad374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span</value>
      <webElementGuid>f4d5e2e3-fc41-4ed3-b9f4-cda33bc995c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
