<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>total points</name>
   <tag></tag>
   <elementGuidId>71da8de3-7f8c-441a-bea9-c91ed1f5f5a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='main']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.totalpoints</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>702a3d3c-ee3f-4b68-b17f-f997f42b8055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>totalpoints</value>
      <webElementGuid>a6db7b35-ea4d-4b0b-9e88-0732cdd04467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>d60c9b5f-b49b-4a5c-8f9a-247cd8d5115e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;gi&quot;]/div[@class=&quot;totalpoints&quot;]</value>
      <webElementGuid>4b18d11e-3da8-498d-9509-a78e7db1777e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='main']/div/div[2]</value>
      <webElementGuid>5153b981-f8ca-47d1-a1e3-d64867ba18dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ik onderhandel graag om tot het best mogelijke resultaat te komen.'])[1]/following::div[1]</value>
      <webElementGuid>ab4b962a-13ff-4482-bcd6-a580182b3d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ook onder stress houd ik het overzicht en doe ik wat er gedaan moet worden.'])[1]/following::div[2]</value>
      <webElementGuid>8c6e02e4-b35f-4145-aff3-e35a66b9b8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[2]/preceding::div[1]</value>
      <webElementGuid>bb36f94e-656f-49aa-8a95-5c1c86e99536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='8']/parent::*</value>
      <webElementGuid>74628784-9a9b-4cef-a5b0-d480cbac7e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]</value>
      <webElementGuid>1d446dd4-9bbd-46c4-bcd1-3120e4bc656e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '8' or . = '8')]</value>
      <webElementGuid>515656e8-2cb1-4fa7-899a-864066849284</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
