<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notification Successfully hired</name>
   <tag></tag>
   <elementGuidId>7c0e4621-cba5-418e-9924-790d569d9357</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.message--JLS.message_success--3GP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@data-katalon, 'flashMessage_success')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d0493095-fff0-4289-ba7b-f95124fcfad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message--JLS message_success--3GP</value>
      <webElementGuid>d15e60f9-70f3-45a2-9e59-d737b4786439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The candidate has been succesfully hired!</value>
      <webElementGuid>26d7685a-a3f3-49f7-b079-299904e0c263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper--2Ws&quot;]/div[@class=&quot;list--h47&quot;]/div[@class=&quot;message--JLS message_success--3GP&quot;]</value>
      <webElementGuid>7cdeb0e6-3455-44a0-bef4-f9028b9c28fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>flashMessage_success</value>
      <webElementGuid>cb265a3d-4db7-4aaa-a0a9-9c5d493c5e54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div</value>
      <webElementGuid>3542177f-d3f2-4b59-842c-2a09d130b38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript required'])[1]/following::div[4]</value>
      <webElementGuid>ab451363-f382-47f8-b73e-85fe353a00a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analytics'])[1]/preceding::div[4]</value>
      <webElementGuid>6d81895e-9efd-4c52-970d-db71726299bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>de1d3a65-5919-446f-9852-3f8f56b29250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'The candidate has been succesfully hired!' or . = 'The candidate has been succesfully hired!')]</value>
      <webElementGuid>e010f515-af9b-4918-ba59-2c21bf25d5f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
