<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Client</name>
   <tag></tag>
   <elementGuidId>be0d7695-191d-4692-96db-9fa9040be013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.controlGroup--3ay.controlGroup--1xQ > div.component--17Y > div.textbox--24h.readOnly--2rR.inline--1PL > div.inner--2u7 > input.input--3G-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name=''])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a96d0ee8-20eb-4d20-8ff1-17ce436bc100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>4ca05d31-18ae-4cd8-86b5-8c808223be7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87852382-3477-468c-b158-5a1d24624fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input--3G-</value>
      <webElementGuid>e5a01ae8-61ba-485f-8c4f-1cac24d62278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>153b85d7-84ab-466d-9006-700c111d64ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>33b6483b-a8d5-4344-a3ea-8e91a84bc209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>candidateDivisionClient</value>
      <webElementGuid>c559a729-a5de-4037-92c0-bee454a37c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Test Client 2</value>
      <webElementGuid>32d6377d-8a3f-4611-9d3a-d92fe64c37e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-container&quot;)/div[@class=&quot;content content--3Nx&quot;]/div[@class=&quot;widgetWrapper--3SO&quot;]/div[2]/div[@class=&quot;widget--pVX&quot;]/div[@class=&quot;controlGroup--3ay controlGroup--1xQ&quot;]/div[@class=&quot;component--17Y&quot;]/div[@class=&quot;textbox--24h readOnly--2rR inline--1PL&quot;]/div[@class=&quot;inner--2u7&quot;]/input[@class=&quot;input--3G-&quot;]</value>
      <webElementGuid>6836c509-053a-41f7-9bd2-ec9c34c5fef9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name=''])[5]</value>
      <webElementGuid>b9fd8178-8291-428b-bd6d-d6eea4415d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-container']/div/div[2]/div[2]/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>4787ccd8-b222-45f1-a651-47886c06544e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>ac969819-76f2-4ef0-a297-ba966886bfe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter' and @type = 'text']</value>
      <webElementGuid>ccd5bf42-42a5-4b5c-90c1-fb77f05eb8c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
