<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Groups</name>
   <tag></tag>
   <elementGuidId>b7f80971-20cc-463d-b3f7-f18b500c2258</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name=''])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31329e21-ec93-41b6-b71e-46dfcb9671a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>4f6801bf-f8f8-44ff-a3b4-bd1049fd9023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>779eb96c-8441-4ab4-b634-83ea2c70c2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input--3G-</value>
      <webElementGuid>35868d75-bdcb-4307-b893-fa0ec52e5254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>98cc7d14-1487-4869-ba92-0fad6c4f55ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>4ce9de65-8142-483a-bc92-5f546fa0e0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>candidateDivisionGroups</value>
      <webElementGuid>89118e54-1ba7-430f-aa8a-b60ee0d39964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>729f9ecf-3acb-4353-844b-6f40a33aa56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-container&quot;)/div[@class=&quot;content content--3Nx&quot;]/div[@class=&quot;widgetWrapper--3SO&quot;]/div[2]/div[@class=&quot;widget--pVX&quot;]/div[@class=&quot;controlGroup--3ay controlGroup--1xQ&quot;]/div[@class=&quot;component--17Y&quot;]/div[@class=&quot;textbox--24h readOnly--2rR inline--1PL&quot;]/div[@class=&quot;inner--2u7&quot;]/input[@class=&quot;input--3G-&quot;]</value>
      <webElementGuid>5c0f77d8-294b-4407-9ee9-ea6c7f7549d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name=''])[8]</value>
      <webElementGuid>1e40206a-affb-497d-8ff6-f4be2b1f63ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-container']/div/div[2]/div[2]/div[2]/div[5]/div/div/div/input</value>
      <webElementGuid>8156e59a-bae7-430b-9bd0-ca07215c727a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/div/div/input</value>
      <webElementGuid>ed88f173-578f-4f09-8af1-5c93f5032bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter' and @type = 'text']</value>
      <webElementGuid>50193e26-63b6-4f42-8de8-5f1a4d4345f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
