<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button EN</name>
   <tag></tag>
   <elementGuidId>57ace2a6-bc04-4b8c-b877-5720fbdd2773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.languageItem--3MB.languageItem_active--3aU</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b0bd38e-c7c3-497c-8488-01e8a504414f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52bdfb05-c057-4d05-8c1c-f94756080516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>languageItem--3MB languageItem_active--3aU</value>
      <webElementGuid>84d060d1-7a8f-44b0-b9a9-b6a04e31af5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-katalon</name>
      <type>Main</type>
      <value>langSwitcher_en</value>
      <webElementGuid>08a47e64-72ed-411b-ac81-d250d90f619d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>c74f6897-e098-4f11-89c8-e2be4f637899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[6]/div[@class=&quot;styles_overlay__CLSq- modalOverlay overlay--1b0&quot;]/div[@class=&quot;styles_modal__gNwvD modalV2--3P2 modal--1KT&quot;]/div[1]/div[@class=&quot;section--1sp&quot;]/div[@class=&quot;content--1Ky&quot;]/div[1]/div[@class=&quot;controlGroup--3ay&quot;]/div[@class=&quot;component--17Y&quot;]/div[@class=&quot;paddingBox--sGL paddingBox_topScanty--1aL&quot;]/div[@class=&quot;languagesWrapper--1Ty&quot;]/button[@class=&quot;languageItem--3MB languageItem_active--3aU&quot;]</value>
      <webElementGuid>94e61ec4-1c7a-4cd9-8797-2b56a641ae4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>9720c30e-0288-4bb7-87b6-044f47e1054a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/following::button[1]</value>
      <webElementGuid>9d8644de-980c-4d6c-abdc-42bcfce7d730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Match Report'])[1]/following::button[1]</value>
      <webElementGuid>1a6fd8d8-8d41-4db3-b32b-6a03211a21c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nl'])[1]/preceding::button[1]</value>
      <webElementGuid>cd4fcae6-06e7-438a-b2c7-c4ad34300a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[2]</value>
      <webElementGuid>0b85263b-fb4a-49b9-9488-c8346b65531d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='en']/parent::*</value>
      <webElementGuid>aed059b6-5d20-4378-b476-a19fd9470ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>3b8e9da3-a0d8-4b9c-8702-2ab83cd6711a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'en' or . = 'en')]</value>
      <webElementGuid>a68c3c33-442d-4b28-b545-ccc09f7d6031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
